### ISSUE TITLE
PubNubPackage schemes reference missing targets, cause DVTAssertion failure in Xcode 14 beta which prevents Carthage builds

### ISSUE THREAD

**Issue by SSheldon** [pubnub/swift#111]
The `PubNubPackageDescription` and `PubNubPackageTests` schemes reference missing targets:
* https://github.com/pubnub/swift/blob/6.0.0/PubNub.xcodeproj/xcshareddata/xcschemes/PubNubPackageDescription.xcscheme#L18
* https://github.com/pubnub/swift/blob/6.0.0/PubNub.xcodeproj/xcshareddata/xcschemes/PubNubPackageTests.xcscheme#L18

<img width="919" alt="Screen Shot 2022-08-04 at 3 42 25 PM" src="https://user-images.githubusercontent.com/478311/182969985-4c19587b-096a-4292-983c-671fc760f6a7.png">

A quick grep of the repo suggests these schemes may be unused.

Surprisingly, this also triggers some sort of bug in Xcode 14 beta 4. You can reproduce this by running `carthage build --no-skip-current` in the repo, which results in the following error:
```
A shell task (/usr/bin/xcrun xcodebuild -project PubNub.xcodeproj -scheme PubNubPackageTests -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -showBuildSettings -skipUnavailableActions) failed with exit code 6:
2022-08-04 15:37:54.280 xcodebuild[7575:16759252] [MT] DVTAssertions: ASSERTION FAILURE in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot8/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-21322/IDEFoundation/Execution/RunDestinations/IDERunDestinationCLI.m:566
Details:  Unhandled/unexpected case where no run destinations were produced.
Object:   <IDERunDestinationCLI>
Method:   +resolveRunDestinationsWithWorkspace:scheme:buildAction:schemeCommand:schemeTask:destinationSpecifications:architectures:timeout:runDestinationManager:deviceManager:fallbackPreferredSDK:fallbackPreferredArchitectures:skipUnsupportedDestinations:shouldSkipRunDestinationValidation:didDisambiguate:disambiguatedMatches:disambiguatedMatchesDescription:error:
Thread:   <_NSMainThread: 0x600001a3c1c0>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _sortDevicesForDisplay (in IDEFoundation)
  4   -[Xcode3CommandLineBuildTool _resolveRunDestinationsForBuildAction:] (in Xcode3Core)
  5   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
  6   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
  7   XcodeBuildMain (in libxcodebuildLoader.dylib)
  8   start (in dyld)
```

(This can also be observed by just running the underlying xcode command that Carthage runs, `xcodebuild -project PubNub.xcodeproj -scheme PubNubPackageDescription archive -showBuildSettings -skipUnavailableActions`.)

If these schemes are truly unused, it seems that removing them prevents the Xcode 14 beta issue from being triggered.

**Comment by SSheldon** [comment]
This is still happening in beta 6.

**Comment by parfeon** [comment]
@SSheldon Is Carthage used only for PubNub SDK? SPM integration approach doesn't work for you?

**Comment by SSheldon** [comment]
@parfeon we use Carthage for most of our dependencies because we want to be able to build xcframeworks that we can cache between builds; [SPM has thus far deferred supporting an "artifact cache" use case](https://github.com/apple/swift-evolution/blob/main/proposals/0272-swiftpm-binary-dependencies.md#general-approach).

Are these schemes used in some way that I'm missing which makes it difficult to remove them?

**Comment by parfeon** [comment]
Changes prepared. Waiting for review.
