### ISSUE TITLE
Building example app fails if the repo is checked out as directory with a name besides "swift"

### ISSUE THREAD

**Issue by SSheldon** [pubnub/swift#113]
Repro steps:
1. `git clone https://github.com/pubnub/swift.git PubNub`
2. `open PubNub/PubNub.xcworkspace`
3. Select "Example-iOS" scheme and build

The build will fail with:
> Missing package product ...
> Package resolution errors must be fixed before building

Inspecting the "Resolve Packages" action shows that it failed with:
> unable to override package 'PubNub' because its identity 'swift' doesn't match override's identity (directory name) 'pubnub'

It appears that this happens because the example app adds PubNub as a remote package reference _and_ overrides that with a local package reference. SPM appears to only allow this when the local package is in a directory whose name matches the last component of the remote repo URL.

Removing the remote package reference (and using the local package directly instead) seems to fix this issue.

**Comment by SSheldon** [comment]
Also fyi when reproing this on latest master I first hit another issue in package resolution:
> could not find a branch named ‘features/CLEN-351_VSP-modules’ in https://github.com/pubnub/swift.git

Looks like the Examples xcodeproj was changed in 2fc06558f532a52d204b7d2ea7e8c0f7b26253af to reference a now-deleted branch:
https://github.com/pubnub/swift/blob/98efba04df88d9a303acf3015f1a7ced5b9916b5/Examples/Examples.xcodeproj/project.pbxproj#L463

To work around this locally I updated the project back to using the master branch.

**Comment by parfeon** [comment]
@SSheldon thank you for reporting. Will work along with schemas without targets as well.
