### ISSUE TITLE
Some PubNub.xcodeproj targets set `TARGETED_DEVICE_FAMILY` that conflicts with `SUPPORTED_PLATFORMS`, preventing building for specific simulators

### ISSUE THREAD

**Issue by SSheldon** [pubnub/swift#150]
I've observed this problem for `PubNubSpace`, `PubNubUser`, and `PubNubMembership`.

To reproduce:
1. Find the device ID of an affected simulator, like a watchOS simulator, with a command like: `xcrun simctl list devices 'Apple Watch Series 9 (41mm)'`. In my case, the device ID is `AA65EFA4-F386-4C67-9AD1-FE86DDC6EC2A`.
2. Attempt to build `PubNubUser` for that simulator, with a command like the following:

```
xcodebuild -workspace PubNub.xcworkspace -scheme PubNubUser -sdk watchsimulator -destination platform=watchOS\ Simulator,id=AA65EFA4-F386-4C67-9AD1-FE86DDC6EC2A build
```

This command will fail with:
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:AA65EFA4-F386-4C67-9AD1-FE86DDC6EC2A }
```

The available destinations notably include iOS simulators, but not watchOS or tvOS simulators.

This behavior does _not_ happen for the `PubNub` framework.

The cause appears to be that these frameworks set `SUPPORTED_PLATFORMS` to include watchOS and tvOS, by inheriting the default setting from the project:
https://github.com/pubnub/swift/blob/6980f9f03aad3996dd90cdd50584ec1ee95abb99/PubNub.xcodeproj/project.pbxproj#L4362

However, they also set `TARGETED_DEVICE_FAMILY` to _only_ iPhone (1) and iPad (2):
https://github.com/pubnub/swift/blob/6980f9f03aad3996dd90cdd50584ec1ee95abb99/PubNub.xcodeproj/project.pbxproj#L3447

In contrast, for the `PubNub` target, `TARGETED_DEVICE_FAMILY` is set to include tvOS (3) and watchOS (4):
https://github.com/pubnub/swift/blob/6980f9f03aad3996dd90cdd50584ec1ee95abb99/PubNub.xcodeproj/project.pbxproj#L4269

Removing that setting or setting it to include tvOS and watchOS fixes the issue.

Notably, the repro steps here are comparable to the steps Carthage performs for `carthage build --no-skip-current --use-xcframeworks`, which also reproduces this issue and impacts us weirdos still using Carthage.

**Comment by jguz-pubnub** [comment]
This issue has been fixed in the `7.2.0` release
