### ISSUE TITLE
Double call of `subscribe` disconnect the PubNub

### ISSUE THREAD

**Issue by akuzminskyi** [pubnub/swift#158]
Hi, is it expected behavior if we call `pubNub.subscribe(to: "channel_id")` twice the PubNub disconnects?

I'm using 7.0.0 SDK

**Comment by mohitordex** [comment]
Facing same issue on 7.0.0 SDK

**Comment by jguz-pubnub** [comment]
Hi @akuzminskyi 

Here's a unit test I wrote to reproduce your scenario. Is this what you meant?

```
func testSubscribeTheSameChannel() {
    let expectation = XCTestExpectation(description: "Test Subscribe Twice")
    expectation.assertForOverFulfill = true
    expectation.expectedFulfillmentCount = 2
    
    pubnub.onConnectionStateChange = { newStatus in
      switch newStatus {
      case .connecting:
        expectation.fulfill()
      case .connected:
        expectation.fulfill()
      default:
        XCTFail("Unexpected connection status")
      }
    }
    
    pubnub.subscribe(to: ["channel"])
    pubnub.subscribe(to: ["channel"])
    
    XCTAssertEqual(pubnub.subscribedChannels, ["channel"])
    wait(for: [expectation], timeout: 1.0)
  }
```

**Comment by akuzminskyi** [comment]
@jguz-pubnub yes, looks like that.
try to add an assert after the subscribe lines
```
pubnub.subscribe(to: ["channel"])
pubnub.subscribe(to: ["channel"])
XCTAssertNotEqual(pubnub.connectionStatus, .disconnected)
```

**Comment by akuzminskyi** [comment]
@jguz-pubnub I see you marked it as a bug, can you please let us know from which version we have this issue? to understand the impact of the issue for companies that use the PubNub

**Comment by jguz-pubnub** [comment]
@akuzminskyi this issue occurs in `7.0.0` version only

**Comment by akuzminskyi** [comment]
I can confirm the issue is not happening anymore in 7.1.0 for me.
