### ISSUE TITLE
Add privacy manifest

### ISSUE THREAD

**Issue by ed-smokefree-ai** [pubnub/swift#164]
Starting May 1, 2024 third party SDKs must provide a privacy manifest declaring their usage and reason for particular APIs. One such API used by the PubNub SDK is [creationDateKey](https://developer.apple.com/documentation/foundation/urlresourcekey/1410073-creationdatekey)

It is used in the following places:

https://github.com/pubnub/swift/blob/c58d58e3761010289d395ab2530cb19f38255108/Sources/PubNub/Extensions/FileManager%2BPubNub.swift#L28

https://github.com/pubnub/swift/blob/c58d58e3761010289d395ab2530cb19f38255108/Sources/PubNub/Extensions/FileManager%2BPubNub.swift#L52

https://github.com/pubnub/swift/blob/c58d58e3761010289d395ab2530cb19f38255108/Sources/PubNub/Extensions/FileManager%2BPubNub.swift#L68

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393

This API for accessing file timestamps requires a reason for use. The PubNub SDK should have a privacy manifest for `NSPrivacyAccessedAPICategoryFileTimestamp`.

Warning when uploading app to App Store Connect:

> TMS-91053: Missing API declaration - Your app’s code in the “ExampleApp” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by jguz-pubnub** [comment]
Privacy manifest has been introduced in the newest `7.2.0` version
